# Generated by Django 5.2.2 on 2025-09-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '部署',
                'verbose_name_plural': '部署',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('in_room_time', models.DateTimeField(auto_now_add=True)),
                ('out_room_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '従業員',
                'verbose_name_plural': '従業員',
            },
        ),
    ]
