# Generated by Django 5.2.2 on 2025-09-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
