# Generated by Django 5.2.2 on 2025-09-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_room', '0002_employee_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='部署名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='in_room.department', verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(max_length=100, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='in_room_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入室時間'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='out_room_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='退室時間'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='電話番号'),
        ),
    ]
