# Generated by Django 5.2.2 on 2025-09-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_room', '0003_alter_department_name_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='out_room_time',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='in_room_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入室時間'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='内線番号'),
        ),
    ]
