# Generated by Django 5.2.2 on 2025-09-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in_room', '0004_remove_employee_out_room_time_and_more'),
    ]

    operations = [
    ]
