# Generated by Django 5.2.2 on 2025-09-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_room', '0005_auto_20250923_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='予定'),
        ),
    ]
